dbdata:
  build: ./db
  # fundamental para que non se arranque 2 veces o mysql
  command: echo "hola"

db:
  image: redmine_dbdata
  command: sh -c "/root/start.sh"
  volumes_from: 
    - dbdata
  expose:
    - "3306"

app:
  build: ./app
  command: sh -c "/root/start.sh"
  links: 
    - db:db.local
  ports:
    - "80:80"
